version: '3'
services:
  karyo:
    image: karyo:${tag_name}
    restart: unless-stopped
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:6030"
    container_name: karyo
    ports:
      - 0.0.0.0:6030:6030