version: '3'
services:
  karyo:
    image: karyo:${RELEASE_VERSION}
    restart: unless-stopped
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:6030"
    container_name: karyo
    environment:
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    ports:
      - 0.0.0.0:6030:6030