name: Bot CI-CD
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
#      branches: [main]
      tags:
        - 'prod-*'
        - 'stage-*'

    pull_request:
      branches: [main]
    workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        # Don't forget to add environment vars as secrets in repository settings on GitHub
        with:
          # VPS IP
          host: ${{ secrets.VPS_SSH_HOST }}
          # VPS username
          username: ${{ secrets.VPS_SSH_USERNAME }}
          # SSH key (copy it from your local machine)
          key: ${{ secrets.VPS_SSH_SECRET }}
          # SSH port
          port: ${{ secrets.VPS_SSH_PORT }}
          run: tag_name = github.ref_name
          script: |  
            cd ${{ secrets.PROJECT_PATH }} 
            git pull origin main 
            docker-compose down 
            echo RELEASE_VERSION=${{github.ref_name}} >> .env
            echo EMAIL_USERNAME=${{secrets.EMAIL_USERNAME}} >> .env
            echo EMAIL_PASSWORD=${{secrets.EMAIL_PASSWORD}} >> .env
            docker-compose up --build -d 
            echo "Deleting old image(s)..."
            docker image prune -a -f